import { GoogleGenAI, Modality, Type } from "@google/genai";
import { ClothingItem, UserImage, FitAnalysis } from '../types';
import { dataUrlToParts } from '../utils/imageHelpers';

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });

export const generateClothingItem = async (prompt: string): Promise<string> => {
  try {
    const fullPrompt = `generate a photorealistic, 8k resolution image of ${prompt}. 
    Professional product photography, studio lighting, pure white background. 
    The item must be the only subject, centered. 
    Focus on realistic fabric textures, accurate lighting, and high detail.`;

    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-image-preview',
      contents: {
        parts: [{ text: fullPrompt }],
      },
      config: {
        imageConfig: {
            aspectRatio: "1:1",
            imageSize: "2K",
        },
      },
    });

    if (response.candidates?.[0]?.content?.parts) {
        for (const part of response.candidates[0].content.parts) {
           if (part.inlineData) {
               return part.inlineData.data;
           }
        }
    }

    throw new Error('No image was generated by the API for the clothing item.');
  } catch (error) {
    console.error("Error generating clothing item:", error);
    throw new Error("Failed to generate the custom clothing item. Please try again.");
  }
};

export const generateMeasurements = async (userImage: UserImage, clothingItems: ClothingItem[], height: string | null): Promise<FitAnalysis> => {
  try {
    const userImagePart = {
      inlineData: {
        data: userImage.base64,
        mimeType: userImage.mimeType,
      },
    };

    const clothingDescription = clothingItems.map(item => `- ${item.type}: ${item.description}`).join('\n');
    
    const heightInfo = height 
      ? `The person has provided their height as ${height}. Use this information to accurately scale the pixel dimensions to real-world inches.` 
      : `Assume they are of average height for their apparent gender and build, but prioritize visual proportions.`;

    const textPrompt = `You are an expert AI virtual tailor. Analyze the person in the provided image. ${heightInfo}

    1. COMPREHENSIVE BODY MEASUREMENTS:
    Based on their visible proportions and provided height, estimate the following specific body measurements in inches:
    - Chest / Bust
    - Waist
    - Hips
    - Shoulder Width (seam to seam)
    - Sleeve Length (shoulder to wrist)
    - Inseam (crotch to floor)
    - Neck Circumference
    - Thigh Circumference
    
    Add a brief note regarding body type and sizing advice based on these observations.

    2. GARMENT FIT ANALYSIS:
    Analyze the following selected clothing items:
    ${clothingDescription}

    For each item:
    - Provide a detailed "fitDescription". Go beyond simple labels. Explain how it will interact with the user's specific measurements (e.g., "The shoulders will drape slightly past your natural shoulder line," "The waist is high-rise and will sit comfortably above the hips," "The pant legs will stack at the ankle due to the estimated inseam").
    - Estimate specific garment measurements in inches for a standard size Medium (M), adjusting for any specific style descriptors (like "oversized", "cropped", "baggy", "slim"). 
      - For Tops: Chest width, Body Length, Sleeve Length, Shoulder width.
      - For Pants: Waist width, Inseam length, Rise, Leg Opening.
      - For Shoes/Accessories: General dimensions if applicable.

    Provide the output as a JSON object complying with the specified schema. Do not include any markdown formatting.`;

    const textPart = { text: textPrompt };

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: {
        parts: [userImagePart, textPart],
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            personMeasurements: {
              type: Type.OBJECT,
              properties: {
                measurements: {
                  type: Type.ARRAY,
                  items: {
                    type: Type.OBJECT,
                    properties: {
                      name: { type: Type.STRING },
                      value: { type: Type.STRING },
                    },
                    required: ['name', 'value'],
                  }
                },
                notes: { type: Type.STRING }
              },
              required: ['measurements', 'notes'],
            },
            clothingFit: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  itemName: { type: Type.STRING },
                  itemType: { type: Type.STRING },
                  fitDescription: { type: Type.STRING },
                  garmentMeasurements: {
                    type: Type.ARRAY,
                    items: {
                      type: Type.OBJECT,
                      properties: {
                        name: { type: Type.STRING },
                        value: { type: Type.STRING },
                      },
                      required: ['name', 'value'],
                    }
                  },
                },
                required: ['itemName', 'itemType', 'fitDescription', 'garmentMeasurements'],
              },
            },
          },
          required: ['personMeasurements', 'clothingFit'],
        },
      },
    });

    const jsonResponse = JSON.parse(response.text);
    return jsonResponse as FitAnalysis;

  } catch (error) {
    console.error("Error generating measurements:", error);
    throw new Error("Failed to generate fit analysis. Please try again.");
  }
};


export const generateOutfit = async (userImage: UserImage, clothingItems: ClothingItem[]): Promise<string> => {
  try {
    const userImagePart = {
      inlineData: {
        data: userImage.base64,
        mimeType: userImage.mimeType,
      },
    };

    // Prepare the parts array with the user image first
    const parts: ( { inlineData: { data: string; mimeType: string; }; } | { text: string; } )[] = [userImagePart];

    // Add clothing images
    const clothingImageParts = clothingItems.map((item) => {
        if (item.imageUrl.startsWith('data:')) {
            const { base64, mimeType } = dataUrlToParts(item.imageUrl);
            return { inlineData: { data: base64, mimeType } };
        }
        return null;
    }).filter((part): part is { inlineData: { data: string; mimeType: string; } } => part !== null);

    parts.push(...clothingImageParts);

    const clothingDescription = clothingItems.map(item => item.description).join(', ');
    
    let textPrompt: string;
    if (clothingImageParts.length > 0) {
      // Enhanced prompt for exact replication
      textPrompt = `You are a professional digital tailor. 
      Reference Images Provided:
      1. The User (Model) - Preserve their face, body, pose, and background exactly.
      2. The Clothing Item(s) - The exact garment to be worn.

      TASK:
      Generate a photorealistic image of the User wearing the Clothing Item(s).

      CRITICAL INSTRUCTIONS:
      - EXACT REPLICATION: The clothing in the output MUST be an exact visual copy of the provided Clothing Image. Match the logo ("1OF1"), graphics, texture, fabric weight, and color perfectly. 
      - LOGO PLACEMENT: The "1OF1" logo must be visible, centered on the chest, and crisp, exactly as it appears in the Clothing Image.
      - FIT & SILHOUETTE: Respect the fit described (e.g. "oversized", "long sleeve"). The shirt should drape naturally on the user's body.
      - PRESERVE IDENTITY: Do NOT change the user's face or identity.
      - PRESERVE BACKGROUND: Do NOT change the background.

      Item Description: ${clothingDescription}`;
    } else {
      textPrompt = `Generate a realistic, non-edited photo of the person in the provided image now wearing ${clothingDescription}. Maintain the original background, the person's pose, and their facial expression exactly as they are in the original photo. The new clothing should fit the person's body naturally. Only change the clothing.`;
    }

    const textPart = { text: textPrompt };
    parts.push(textPart);


    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: parts,
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });
    
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }

    throw new Error('No image was generated by the API.');
  } catch (error) {
    console.error("Error generating outfit:", error);
    throw new Error("Failed to generate the image. Please try again.");
  }
};

export const customizeOutfit = async (generatedImage: UserImage, instruction: string): Promise<string> => {
    try {
      const imagePart = {
        inlineData: {
          data: generatedImage.base64,
          mimeType: generatedImage.mimeType,
        },
      };
  
      const textPart = {
        text: `Based on the provided image, perform the following modification: "${instruction}". Only alter the specified clothing item. The person, background, and any other clothing must remain completely unchanged. The result should be a realistic, non-edited photo.`,
      };
  
      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [imagePart, textPart],
        },
        config: {
          responseModalities: [Modality.IMAGE],
        },
      });
      
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          return part.inlineData.data;
        }
      }
  
      throw new Error('No image was generated by the API for customization.');
    } catch (error) {
      console.error("Error customizing outfit:", error);
      throw new Error("Failed to apply the customization. Please try again.");
    }
  };